title: Analízis
description: Analízis képletek
logo:
google_analytics:

github_link: https://github.com/nemkin/analizis

remote_theme: jekyll/minima
header_pages: ['']

markdown: kramdown

plugins:
  - jekyll-titles-from-headings
titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true
